language: java
jdk:
- openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_b076cddc14df_key -iv $encrypted_b076cddc14df_iv
  -in project.json.enc -out project.json -d
- chmod +x gradlew
jobs:
  include:
  - stage: build
    script:
    - "./gradlew build -x test"
  - stage: unit-tests
    script:
    - "./gradlew test --tests SimpleSavingsCalculatorTests --tests MortgageCalculatorTest
      --tests CreditCardMinimumPaymentCalculatorTests --tests CCPayoffTest"
    - 
  - stage: integration-tests
    script: "./gradlew test --tests BigBankApplicationTest"

deploy:
  provider: gae
  keyfile: project.json
  project: pp2-group-9
  on:
    branch:
      - master
      - emg-skip-int
      - emg-skip-unit
      - emg-skip-all
  skip_cleanup: true

stages:
- name: build
  if: branch = master OR branch = emg-skip-all OR branch = emg-skip-unit OR branch
    = emg-skip-int OR branch = build
- name: unit-tests
  if: branch = master OR branch = emg-skip-int
- name: integration-tests
  if: branch = master OR branch = emg-skip-unit
