version: "3.8"

services:
  database:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    network_mode: host

  web:
    image: "bbapp"
    ports:
      - "8080:8080"
    network_mode: host

